[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.6",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "psycopg[binary,pool]>=3.2.9",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "supabase>=2.18.0",
    "uvicorn>=0.35.0",
]
